name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          lfs: true
          submodules: true
      - name: Install libserialport
        run:   |
          git clone git://sigrok.org/libserialport
          cd libserialport
          ./autogen.sh
          ./configure
          make
          make install
          cd
        shell: bash
      - name: Install scons
        uses: BSFishy/pip-action@v1
        with:
          packages: scons
      - name: Build Extension
        run: |
          python build.py --extension-only
      - name: Build
        id: build
        uses: krynv/build-godot-action@v1.0.0
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
          projectDir: "project"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
